services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: mikrobloggeriet
      POSTGRES_USER: mikrobloggeriet
      POSTGRES_DB: mikrobloggeriet
    command:
      - "-c"
      - "fsync=off"
    ports:
      - 5432:5432
