#+title: Teodor

* 2023-03-28
** notater
Oddmund, Lars og Richards mikroblogg

1. Hva gjør du akkurat nå?
2. Finner du kvalitet i det?
3. Hvorfor / hvorfor ikke?

Olorm.iterate.no

#+begin_src
Bb tui
git pul l --rebase
FZF for å velge builder
$EDITOR
Save
Git commit og push
#+end_src

#olorm på Slack
Teodor følger opp manuelt i starten, backup fra Magnus (?)
** retro
funka det!

- Var nok jobb i å ta CLI-biten.
- Og ignorerer støtte for flere input-formater for nå.
- Mulig IKI-gjenbruk her er ... lite / optimistisk.
* 2023-03-30
** prat med Lars
1. lars sa han var villig til å prøve en uke
2. tirsdag eller onsdag etter lunsj etter påske fungerte sannsynligvis bra for lars

Ikke hørt med Oddmund og Richard ennå.
Håper vi kan finne et tidspunkt der alle kan være på kontoret.
* 2023-04-16
** Åhh, kjempefornøyd med =olorm.lib=!!!
Dette synes jeg begynner å bli skikkelig bra.
** Og =clerk= og =babashka/fs=!
❤️
** meeeen
Jeg har hardkodet meg inn i at URL til OLORM-er skal være

#+begin_src
/p/$OLORM
#+end_src

ooog nå vil jeg ha

#+begin_src
/o/$OLORM
#+end_src

, selvfølgelig.
*** men meen
jeg kan jo bare fikse routeren, og la filene ligge?

hmm.
