name: Containers
on: { push: {} }

jobs:
  build:
    name: Build
    permissions:
      contents: read
      id-token: write
      packages: write

    strategy:
      fail-fast: false
      matrix:
        include: [ { appling: main, dockerfile: Dockerfile } ]

    runs-on: ubuntu-latest
    steps:
      - uses: 'google-github-actions/auth@v2'
        id: gcp-auth
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_POOL_PROVIDER }}

      - name: Log in to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.GAR_REGISTRY_HOST }}
          username: oauth2accesstoken
          password: ${{ steps.gcp-auth.outputs.auth_token }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: docker-build-meta
        name: Extract metadata (tags, labels) for Docker
        uses: docker/metadata-action@v5
        with:
          images: |-
            ${{ vars.GAR_REGISTRY_URL }}/${{ github.repository }}/${{ matrix.appling }}
            ghcr.io/${{ github.repository }}/${{ matrix.appling }}
          tags: |-
            type=schedule
            type=sha,format=long,prefix=
            type=edge,branch=$repo.default_branch
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - id: docker-push
        name: Build ${{ vars.GAR_REGISTRY_URL }}/${{ github.repository }}/${{
          matrix.appling }}
        uses: docker/build-push-action@v6
        with:
          file: ${{ matrix.dockerfile }}
          labels: ${{ steps.docker-build-meta.outputs.labels }}
          push: true
          tags: ${{ steps.docker-build-meta.outputs.tags }}
