name: clj-kondo static analysis
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Install clj-kondo
      uses: DeLaGuardo/setup-clj-kondo@v1
      with:
        version: '2023.10.20'

    - uses: actions/checkout@v2

    - name: Lint
      run: clj-kondo --fail-level error --lint src
