name: clj-kondo static analysis
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Install clj-kondo
      uses: DeLaGuardo/setup-clj-kondo@master
      with:
        version: '2025.02.20'

    - uses: actions/checkout@v4

    - name: Show clj-kondo version
      run: clj-kondo --version

    - name: Download kondo-configs for libraries
      run: clj-kondo --lint $(clojure -Spath) --dependencies --skip-lint --copy-configs

    - name: Lint
      run: clj-kondo --fail-level warning --lint src
