name: clj-kondo static analysis
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Install clj-kondo
      uses: DeLaGuardo/setup-clj-kondo@master
      with:
        version: '2024.09.27'

    - uses: actions/checkout@v2

    - name: Lint
      run: clj-kondo --fail-level warn --lint src test
