name: clj-kondo static analysis
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

    - name: Install Java
      uses: actions/setup-java@master
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@master
      with:
        cli: latest

    - name: Install clj-kondo
      uses: DeLaGuardo/setup-clj-kondo@master
      with:
        version: '2025.04.07'

    - uses: actions/checkout@v5

    - name: Show clj-kondo version
      run: clj-kondo --version

    - name: Download kondo-configs for libraries
      run: clj-kondo --lint $(clojure -Spath) --dependencies --skip-lint --copy-configs

    - name: Lint
      run: clj-kondo --fail-level warning --lint src
